### PR TITLE
[MM-32631] Adding fleet controller cronjob module

### PR DESCRIPTION
**Pull request by stylianosrigas**
#### Summary
- Adding module that will deploy the Fleet Controller cronjob. This refers to first time deployment only. Then managed by Flux. 

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-32631

### CODE REVIEW

**Review by gabrieljackson — COMMENTED** [review]
I have one more change I would like to get in which will require one more env var for webhooks. 

https://github.com/mattermost/fleet-controller/pull/7

**Comment by stylianosrigas** [comment]
> I have one more change I would like to get in which will require one more env var for webhooks.
> 
> [mattermost/fleet-controller#7](https://github.com/mattermost/fleet-controller/pull/7)

Sweet added. I will keep this open until we have the final setup :)

**Review by gabrieljackson — APPROVED** [review]
Awesome, looks good!

**Review by gabrieljackson — APPROVED** [review]

**Review by angeloskyratzakos — APPROVED** [review]
👍

**Pull request merged**
