### PR TITLE
Separate nginx charts to internal and public

### PR DESCRIPTION
**Pull request by stafot**
#### Summary
Separate nginx charts to internal and public

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32273

### CODE REVIEW

**Review by stylianosrigas — APPROVED** [review]
That looks good. The big changes are in the values files so good to go here 👍

**Review by angeloskyratzakos — APPROVED** [review]
LGTM

**Comment by ethervoid** [comment]
I've found that I needed to change this part:

```diff
diff --git a/terraform/aws/modules/provisioner/route53.tf b/terraform/aws/modules/provisioner/route53.tf
index fbceaa2..3bf5548 100644
--- a/terraform/aws/modules/provisioner/route53.tf
+++ b/terraform/aws/modules/provisioner/route53.tf
@@ -1,7 +1,7 @@
 data "kubernetes_service" "nginx-internal" {
   metadata {
-    name      = "nginx-ingress-nginx-controller-internal"
-    namespace = "nginx"
+    name      = "nginx-internal-ingress-nginx-controller"
+    namespace = "nginx-internal"
   }
 }
```

**Comment by stafot** [comment]
@ethervoid Ack,I will add it on this PR. Thanks!

**Pull request merged**
