### PR TITLE
feat: Create RDS Cloudwatch alarms dedicated module

### PR DESCRIPTION
**Pull request by toninis**
#### Summary

- Created cloudwatch alarm dedicated module for terragrunt use

@stafot when merged we can incorporate it in the aurora module for consistency. WDYT ? It's the same code. 

#### Ticket Link

https://mattermost.atlassian.net/browse/CLD-5351

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by phoinixgrr** [comment]
Awesome! 

As a release team, we maintain IAC code in :
- https://github.com/mattermost/release-iac
- https://github.com/mattermost/release-iac-modules

We now also have IAC code in 
- https://github.com/mattermost/mattermost-cloud-monitoring


1/5 , Not 100% on having this on https://github.com/mattermost/mattermost-cloud-monitoring
We also have https://github.com/mattermost/release-iac-modules .  Isn't this opening up the scope?

**Comment by stafot** [comment]
@toninis LGTM and reasonable choice.

**Comment by toninis** [comment]
> 

cc: @spirosoik We 've discussed to ditch the release-iac-modules repo in favor of this one at least until we come up with a global strategy for the whole platform team .

**Comment by toninis** [comment]
> Awesome!
> 
> As a release team, we maintain IAC code in :
> 
> * https://github.com/mattermost/release-iac
> * https://github.com/mattermost/release-iac-modules
> 
> We now also have IAC code in
> 
> * https://github.com/mattermost/mattermost-cloud-monitoring
> 
> 1/5 , Not 100% on having this on https://github.com/mattermost/mattermost-cloud-monitoring We also have https://github.com/mattermost/release-iac-modules . Isn't this opening up the scope?

cc: @spirosoik We 've discussed to ditch the release-iac-modules repo in favor of this one at least until we come up with a global strategy for the whole platform team .

**Comment by phoinixgrr** [comment]
> > Awesome!
> > As a release team, we maintain IAC code in :
> > 
> > * https://github.com/mattermost/release-iac
> > * https://github.com/mattermost/release-iac-modules
> > 
> > We now also have IAC code in
> > 
> > * https://github.com/mattermost/mattermost-cloud-monitoring
> > 
> > 1/5 , Not 100% on having this on https://github.com/mattermost/mattermost-cloud-monitoring We also have https://github.com/mattermost/release-iac-modules . Isn't this opening up the scope?
> 
> cc: @spirosoik We 've discussed to ditch the release-iac-modules repo in favor of this one at least until we come up with a global strategy for the whole platform team .

Makes sense. Thanks for the heads up. 
🚀 :shipit:

**Review by phoinixgrr — APPROVED** [review]

**Review by spirosoik — APPROVED** [review]

**Pull request merged**
