### PR TITLE
remove PVC and update label for the provisioner installation

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
 - Remove the PV from the provisioner per https://github.com/mattermost/mattermost-cloud/pull/123
 - update the deployment for the provisioner installation to add an extra label to not conflict with the main deployment

### CODE REVIEW

**Comment by cpanato** [comment]
note: did not apply in the Test env yet, we can do that after xmas.

so we can hold this merge

**Comment by cpanato** [comment]
@stylianosrigas let me know when we can merge this

**Comment by stylianosrigas** [comment]
@cpanato I am ok to merge it. If we merge it today tomorrow I will deploy in all accounts together with some other changes I made.

**Comment by cpanato** [comment]
@stylianosrigas ok sounds good, merging

**Pull request merged**
